### ISSUE TITLE
NetworkError on POST request with fetch API

### ISSUE THREAD

**Issue by mazmap** [Matteo-Dev/musescore-dld#1]
In src/popup/dld-menu.js the function asynchronous function `getSheetDataURL` (listed below) handles a POST request performed with the fetch API. End route on server ("/") is correctly defined, as can be checked by using postman (`POST https://msdld.mertz-es.de`). Also visible in postman: The `Access-Control-Allow-Origin` response header is set correctly to `"*"`.

```js
const message = document.getElementById("message");
...
const getSheetDataURL = async (url) => {
    message.innerText = url;
    return fetch("https://msdld.mertz-es.de/", {
        method: 'POST', // or 'PUT'
        headers: {
            'Content-Type': 'application/json',
        },
        body: JSON.stringify({url: url}),
    })
        .then(r => r.json())
        .then(resBody => resBody.dataURL)
        .catch(e => message.innerText = e)
}
```
The `message` DOM element is just used for debugging purposes to check 1. if an url (a string) has been passed correctly to the function (it has) and 2. to display the error message that states as following: `TypeError: NetworkError when attempting to fetch resource.`. Such an error message usually suggest a CORS-issue. But when instead performing a simple GET request (and subsequently changing the express handler from `app.post` to `app.get` - see below), no `NetworkError` occurs and the request is correctly handled on server- and client-side. 

For the sake of completeness, here's the code of the server backend handling the post request: 
```js
const express = require("express");
const bodyParser = require("body-parser");
const cors = require("cors"); // usage: https://github.com/expressjs/cors#usage
const app = express();

app.use(bodyParser.json());

app.post("/", cors(), (req, res)=>{
    console.log(req.body);
    res.header("Access-Control-Allow-Origin", "*");
    res.send({msg:"test successful"})
});
```

**Comment by Matteo-Dev** [comment]
simply add `app.options('*', cors())` before post handler

**Comment by mazmap** [comment]
simply add `app.options('*', cors())` before post handler, then cors is handled correctly on pre-flight request
